### ISSUE TITLE
Neoforge 1.21.0-1.1.8, game crashes when making any entity follow

### ISSUE THREAD

**Issue by RedRonin73** [SmileycorpMC/Atlas-Lib#5]
Incredible mod, love the simplicity! Unfortunately, using the latest version of neoforge results in consistent crashing anytime I attempt to make an entity follow me. After clicking on them with H or SHIFT+RMB the game manages squeak out a few frames slapping the "Following" tag on the entity before an unrecoverable error sends me back to the desktop. Crash report is below, let me know what else you might need should you decide to check this out. Have a good one!

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-09-22 16:22:13
Description: Ticking entity

java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.LivingEntity.isAddedToWorld()'
	at TRANSFORMER/followme@1.21.0-1.1.8/net.smileycorp.followme.common.ai.FollowUserGoal.canUse(FollowUserGoal.java:44) ~[Follow-Me-1.21.0-1.1.8.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.ai.goal.WrappedGoal.canUse(WrappedGoal.java:22) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:777) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2705) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.aiStep(Mob.java:559) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:128) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:55) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.tick(Mob.java:351) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at TRANSFORMER/followme@1.21.0-1.1.8/net.smileycorp.followme.common.ai.FollowUserGoal.canUse(FollowUserGoal.java:44) ~[Follow-Me-1.21.0-1.1.8.jar%23185!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.ai.goal.WrappedGoal.canUse(WrappedGoal.java:22) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.serverAiStep(Mob.java:777) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:2705) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.aiStep(Mob.java:559) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:128) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:55) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.tick(Mob.java:351) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
-- Entity being ticked --
Details:
	Entity Type: minecraft:pig (net.minecraft.world.entity.animal.Pig)
	Entity ID: 60
	Entity Name: Pig
	Entity's Exact location: 29.80, 72.00, -73.76
	Entity's Block location: World: (29,72,-74), Section: (at 13,8,6 in 1,4,-5; chunk contains blocks 16,-64,-80 to 31,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['RedWraith73'/7, l='ServerLevel[New World]', x=30.27, y=72.00, z=-75.08]]
	Chunk stats: 3181
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,97,0), Section: (at 0,1,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 382 game time, 382 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 73418 (now: false), thunder time: 51276 (now: false)
	Known server brands: neoforge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 314
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.fillReportDetails(ServerLevel.java:1718) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1040) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23182!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1472468976 bytes (1404 MiB) / 5234491392 bytes (4992 MiB) up to 49392123904 bytes (47104 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: Intel(R) UHD Graphics 770
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.4577
	Graphics card #1 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 16380.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 69401.50
	Virtual memory used (MiB): 31790.89
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 1028.74
	Space in storage for jna.tmpdir (MiB): available: 99059.45, total: 1906514.25
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 99059.45, total: 1906514.25
	Space in storage for io.netty.native.workdir (MiB): available: 99059.45, total: 1906514.25
	Space in storage for java.io.tmpdir (MiB): available: 99059.45, total: 1906514.25
	Space in storage for workdir (MiB): available: 99059.45, total: 1906514.25
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx46G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=128M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['RedWraith73'/7, l='ServerLevel[New World]', x=30.27, y=72.00, z=-75.08]]
	Active Data Packs: vanilla, mod_data, mod/followme (incompatible), mod/atlaslib (incompatible), mod/neoforge
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/atlaslib (incompatible), mod/followme (incompatible), mod/neoforge, mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 6859806589493318560
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Launched Version: neoforge-21.1.57
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.24.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.24.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.24.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Follow-Me-1.21.0-1.1.8.jar                        |Follow Me                     |followme                      |1.21.0-1.1.8        |Manifest: NOSIGNATURE
		Atlas-Lib-1.21.0-1.1.14.jar                       |Atlas Lib                     |atlaslib                      |1.21.0-1.1.14       |Manifest: NOSIGNATURE
		neoforge-21.1.57-universal.jar                    |NeoForge                      |neoforge                      |21.1.57             |Manifest: NOSIGNATURE
	Crash Report UUID: 6f77d6a6-e66f-4927-9736-149d29e253d4
	FML: 4.0.24
	NeoForge: 21.1.57

**Comment by RedRonin73** [comment]
Posted to wrong mod repo
